# -*- coding: utf-8 -*-
"""mongo_rpg

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16SvVfj3SUU8pm24lyW3glJvoC92l9QqM
"""

!curl ipecho.net/plain

mongo_password = 'blazingsaddles'

!pip install pymongo

import pymongo

client = pymongo.MongoClient(
    "mongodb://aufeld:ilovemyfiance@cluster0-shard-00-00-dipw9.mongodb.net:27017,cluster0-shard-00-01-dipw9.mongodb.net:27017,cluster0-shard-00-02-dipw9.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.test

db

db.test.count_documents({'x': 1})

db.test.insert_one({'x': 1})

db.test.count_documents({'x': 1})

curs = db.test.find({'x': 1})

cleric_doc = {
    'character_ptr_id' : 1
    'character_discipline' : 'using_shield'
    'character_speciality' : 'mana'
}

fighter_doc = {
    'character_ptr_id' : 2
    'character_discipline' : 'using_shield'
    'character_speciality' : 'rage'
}

mage_doc = {
    'character_ptr_id' : 3
    'character_discipline' : 'has_pet'
    'character_speciality' : 'mana'
}

necromancer_doc = {
    'character_ptr_id' : 4
    'character_discipline' : 'talisman_charged'
}

thief_doc = {
    'character_ptr_id' : 5
    'character_discipline' : 'is_sneaking'
    'character_speciality' : 'energy'
}


all_docs = [cleric_doc, fighter_doc, mage_doc, necromancer_doc, theif_doc]

db.test.insert_many(all_docs)

list(db.test.find())

more_docs = []
for i in range(10):
  doc = {'even': i % 2 == 0}
  doc['value'] = i
  more_docs.append(doc)
  
more_docs

db.test.insert_many(more_docs)

list(db.test.find({'even': True, 'value': 0}))

db.test.insert_one({'rpg_character': rpg_character})

db.test.find_one({'rpg_character': rpg_character})

rpg_doc = {
    'sql_key': rpg_character[0],
    'name': rpg_character[1],
    'hp': rpg_character[2],
    'level': rpg_character[3]
}
db.test.insert_one(rpg_doc)

